"""Add last_scraped_at to companies

Revision ID: 3c59aae07314
Revises: 2ddb63f4447f
Create Date: 2025-11-08 15:50:10.722576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c59aae07314'
down_revision = '2ddb63f4447f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_scraped_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('companies', schema=None) as batch_op:
        batch_op.drop_column('last_scraped_at')

    # ### end Alembic commands ###
