"""Add profile fields

Revision ID: a1b2c3d4e5f6
Revises: cd4f9f08cab3
Create Date: 2025-01-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'cd4f9f08cab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    existing_cols = [col['name'] for col in inspector.get_columns('profiles')]
    
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        if 'email' not in existing_cols:
            batch_op.add_column(sa.Column('email', sa.String(length=255), nullable=True))
        if 'phone' not in existing_cols:
            batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        if 'company' not in existing_cols:
            batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))
        if 'job_title' not in existing_cols:
            batch_op.add_column(sa.Column('job_title', sa.String(length=255), nullable=True))
        if 'location' not in existing_cols:
            batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        if 'industry' not in existing_cols:
            batch_op.add_column(sa.Column('industry', sa.String(length=255), nullable=True))
        if 'scraped_at' not in existing_cols:
            batch_op.add_column(sa.Column('scraped_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('scraped_at')
        batch_op.drop_column('industry')
        batch_op.drop_column('location')
        batch_op.drop_column('job_title')
        batch_op.drop_column('company')
        batch_op.drop_column('phone')
        batch_op.drop_column('email')

    # ### end Alembic commands ###

