"""Add jobs table

Revision ID: f6e5d4c3b2a1
Revises: a1b2c3d4e5f6
Create Date: 2025-01-20 10:01:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'f6e5d4c3b2a1'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if jobs table exists and has old structure
    from sqlalchemy import inspect, text
    conn = op.get_bind()
    inspector = inspect(conn)
    
    if 'jobs' in inspector.get_table_names():
        # Table exists - check if it needs to be altered
        existing_cols = [col['name'] for col in inspector.get_columns('jobs')]
        
        # Add missing new columns if they don't exist
        if 'job_type' not in existing_cols:
            op.add_column('jobs', sa.Column('job_type', sa.String(length=50), nullable=True))
        if 'total_items' not in existing_cols:
            op.add_column('jobs', sa.Column('total_items', sa.Integer(), nullable=True, server_default='0'))
        if 'completed_items' not in existing_cols:
            op.add_column('jobs', sa.Column('completed_items', sa.Integer(), nullable=True, server_default='0'))
        if 'success_count' not in existing_cols:
            op.add_column('jobs', sa.Column('success_count', sa.Integer(), nullable=True, server_default='0'))
        if 'failed_count' not in existing_cols:
            op.add_column('jobs', sa.Column('failed_count', sa.Integer(), nullable=True, server_default='0'))
        if 'result_data' not in existing_cols:
            op.add_column('jobs', sa.Column('result_data', sa.Text(), nullable=True))
        if 'error_message' not in existing_cols:
            op.add_column('jobs', sa.Column('error_message', sa.Text(), nullable=True))
        if 'completed_at' not in existing_cols:
            op.add_column('jobs', sa.Column('completed_at', sa.DateTime(), nullable=True))
        
        # Ensure legacy fields exist (for backward compatibility)
        if 'task_name' not in existing_cols:
            op.add_column('jobs', sa.Column('task_name', sa.String(length=255), nullable=True))
        if 'result' not in existing_cols:
            op.add_column('jobs', sa.Column('result', sa.JSON(), nullable=True))
        if 'error' not in existing_cols:
            op.add_column('jobs', sa.Column('error', sa.Text(), nullable=True))
        
        # Ensure status column exists and has default
        if 'status' not in existing_cols:
            op.add_column('jobs', sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'))
        else:
            # Update status column to have default if it doesn't
            try:
                op.alter_column('jobs', 'status', server_default='pending')
            except:
                pass  # Server default might already be set or not supported
    else:
        # Table doesn't exist, create it with both legacy and new fields
        op.create_table('jobs',
            sa.Column('job_id', sa.String(length=36), nullable=False),
            sa.Column('tenant_id', sa.String(length=36), nullable=False),
            # Legacy fields (for backward compatibility)
            sa.Column('task_name', sa.String(length=255), nullable=True),
            sa.Column('result', sa.JSON(), nullable=True),
            sa.Column('error', sa.Text(), nullable=True),
            # New fields
            sa.Column('job_type', sa.String(length=50), nullable=True),  # nullable to match model
            sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'),
            sa.Column('total_items', sa.Integer(), nullable=True, server_default='0'),
            sa.Column('completed_items', sa.Integer(), nullable=True, server_default='0'),
            sa.Column('success_count', sa.Integer(), nullable=True, server_default='0'),
            sa.Column('failed_count', sa.Integer(), nullable=True, server_default='0'),
            sa.Column('result_data', sa.Text(), nullable=True),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('completed_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('job_id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###

