"""Add jobs table

Revision ID: f6e5d4c3b2a1
Revises: a1b2c3d4e5f6
Create Date: 2025-01-20 10:01:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import inspect

# revision identifiers, used by Alembic.
revision = 'f6e5d4c3b2a1'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if jobs table exists and has old structure
    from sqlalchemy import inspect, text
    conn = op.get_bind()
    inspector = inspect(conn)
    
    if 'jobs' in inspector.get_table_names():
        # Table exists - check if it needs to be altered
        existing_cols = [col['name'] for col in inspector.get_columns('jobs')]
        required_cols = ['job_id', 'tenant_id', 'job_type', 'status', 'total_items', 
                        'completed_items', 'success_count', 'failed_count', 'result_data', 
                        'error_message', 'created_at', 'updated_at', 'completed_at']
        
        # If table has old structure (task_name, result, error), drop and recreate
        if 'task_name' in existing_cols or 'result' in existing_cols:
            op.drop_table('jobs')
            op.create_table('jobs',
                sa.Column('job_id', sa.String(length=36), nullable=False),
                sa.Column('tenant_id', sa.String(length=36), nullable=False),
                sa.Column('job_type', sa.String(length=50), nullable=False),
                sa.Column('status', sa.String(length=50), nullable=False),
                sa.Column('total_items', sa.Integer(), nullable=True),
                sa.Column('completed_items', sa.Integer(), nullable=True),
                sa.Column('success_count', sa.Integer(), nullable=True),
                sa.Column('failed_count', sa.Integer(), nullable=True),
                sa.Column('result_data', sa.Text(), nullable=True),
                sa.Column('error_message', sa.Text(), nullable=True),
                sa.Column('created_at', sa.DateTime(), nullable=True),
                sa.Column('updated_at', sa.DateTime(), nullable=True),
                sa.Column('completed_at', sa.DateTime(), nullable=True),
                sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
                sa.PrimaryKeyConstraint('job_id')
            )
        # If table already has correct structure, skip
    else:
        # Table doesn't exist, create it
        op.create_table('jobs',
            sa.Column('job_id', sa.String(length=36), nullable=False),
            sa.Column('tenant_id', sa.String(length=36), nullable=False),
            sa.Column('job_type', sa.String(length=50), nullable=False),
            sa.Column('status', sa.String(length=50), nullable=False),
            sa.Column('total_items', sa.Integer(), nullable=True),
            sa.Column('completed_items', sa.Integer(), nullable=True),
            sa.Column('success_count', sa.Integer(), nullable=True),
            sa.Column('failed_count', sa.Integer(), nullable=True),
            sa.Column('result_data', sa.Text(), nullable=True),
            sa.Column('error_message', sa.Text(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.Column('completed_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('job_id')
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    # ### end Alembic commands ###

